; Xdebug configuration
[xdebug]
zend_extension=xdebug

; Xdebug 3.x configuration
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.idekey=PHPSTORM
xdebug.log=/var/log/apache2/xdebug.log
xdebug.log_level=7

; Для отладки через Docker
xdebug.discover_client_host=true
xdebug.remote_connect_back=0

